module;

#define GRAPHICS_IN_MODULE_IMPL
#include "graphics/detail/gmf.h"

export module graphics:magnum;

// ═════════════════════════════════════════════════════════════════════════════
//  Corrade::Containers
// ═════════════════════════════════════════════════════════════════════════════

GRAPHICS_EXPORT
namespace Corrade::Containers
{
using Corrade::Containers::Array;
using Corrade::Containers::arrayAppend;
using Corrade::Containers::arrayInsert;
using Corrade::Containers::arrayReserve;
using Corrade::Containers::arrayResize;
using Corrade::Containers::ArrayView;
using Corrade::Containers::StringView;
} // namespace Corrade::Containers

// ═════════════════════════════════════════════════════════════════════════════
//  Magnum (root namespace — typedefs, tags, classes)
// ═════════════════════════════════════════════════════════════════════════════

GRAPHICS_EXPORT
namespace Magnum
{

// Scalar typedefs
using Magnum::Float;
using Magnum::Int;
using Magnum::UnsignedInt;

// Math typedefs (Magnum::X = Math::X<Float>)
using Magnum::Color3;
using Magnum::Color4;
using Magnum::Deg;
using Magnum::DualQuaternion;
using Magnum::Matrix3;
using Magnum::Matrix3x3;
using Magnum::Matrix4;
using Magnum::Quaternion;
using Magnum::Rad;
using Magnum::Vector2;
using Magnum::Vector2i;
using Magnum::Vector3;

// Tags
using Magnum::NoCreateT;
// NoCreate has internal linkage — include <Corrade/Tags.h> in consumers.

// Classes
using Magnum::Timeline;

// Corrade::Containers namespace alias (Magnum.h provides this so that
// `using namespace Magnum;` makes `Containers::X` resolve correctly)
namespace Containers = ::Corrade::Containers;

} // namespace Magnum

// ═════════════════════════════════════════════════════════════════════════════
//  Magnum::Animation
// ═════════════════════════════════════════════════════════════════════════════

GRAPHICS_EXPORT
namespace Magnum::Animation
{
using Magnum::Animation::Extrapolation;
using Magnum::Animation::Track;
} // namespace Magnum::Animation

// ═════════════════════════════════════════════════════════════════════════════
//  Magnum::GL
// ═════════════════════════════════════════════════════════════════════════════

GRAPHICS_EXPORT
namespace Magnum::GL
{

// Classes
using Magnum::GL::AbstractShaderProgram;
using Magnum::GL::Buffer;
using Magnum::GL::DefaultFramebuffer;
using Magnum::GL::Mesh;
using Magnum::GL::Renderer;
using Magnum::GL::Shader;

// Enums
using Magnum::GL::BufferUsage;
using Magnum::GL::FramebufferClear;
using Magnum::GL::MeshIndexType;
using Magnum::GL::MeshPrimitive;

// Globals
using Magnum::GL::defaultFramebuffer;

// Enum-set operators (generated by CORRADE_ENUMSET_OPERATORS in the
// Magnum::GL namespace; ADL cannot find them through modules unless
// they are explicitly exported).
using Magnum::GL::operator|;
using Magnum::GL::operator&;
using Magnum::GL::operator^;
using Magnum::GL::operator~;

} // namespace Magnum::GL

// ═════════════════════════════════════════════════════════════════════════════
//  Magnum::Math
// ═════════════════════════════════════════════════════════════════════════════

GRAPHICS_EXPORT
namespace Magnum::Math
{

// Core templates
using Magnum::Math::Color3;
using Magnum::Math::Color4;
using Magnum::Math::Deg;
using Magnum::Math::DualQuaternion;
using Magnum::Math::Matrix3;
using Magnum::Math::Matrix4;
using Magnum::Math::Quaternion;
using Magnum::Math::Rad;
using Magnum::Math::RectangularMatrix;
using Magnum::Math::Vector;
using Magnum::Math::Vector2;
using Magnum::Math::Vector3;
using Magnum::Math::Vector4;

// Cubic Hermite interpolation types
using Magnum::Math::CubicHermite;
using Magnum::Math::CubicHermite2D;
using Magnum::Math::CubicHermite3D;
using Magnum::Math::CubicHermiteComplex;
using Magnum::Math::CubicHermiteQuaternion;

// Tags
using Magnum::Math::IdentityInitT;
// IdentityInit has internal linkage — include <Magnum/Math/Tags.h> in consumers.

// Interpolation / math functions
using Magnum::Math::abs;
using Magnum::Math::asin;
using Magnum::Math::clamp;
using Magnum::Math::cross;
using Magnum::Math::dot;
using Magnum::Math::isInf;
using Magnum::Math::lerp;
using Magnum::Math::select;
using Magnum::Math::slerp;
using Magnum::Math::slerpShortestPath;
using Magnum::Math::splerp;

} // namespace Magnum::Math

// ═════════════════════════════════════════════════════════════════════════════
//  Magnum::Math::Literals
// ═════════════════════════════════════════════════════════════════════════════

GRAPHICS_EXPORT
namespace Magnum::Math::Literals
{
using Magnum::Math::Literals::operator""_rgbf;
} // namespace Magnum::Math::Literals

// ═════════════════════════════════════════════════════════════════════════════
//  Magnum::MeshTools
// ═════════════════════════════════════════════════════════════════════════════

GRAPHICS_EXPORT
namespace Magnum::MeshTools
{
using Magnum::MeshTools::compile;
} // namespace Magnum::MeshTools

// ═════════════════════════════════════════════════════════════════════════════
//  Magnum::Platform
// ═════════════════════════════════════════════════════════════════════════════

GRAPHICS_EXPORT
namespace Magnum::Platform
{
using Magnum::Platform::Application;
} // namespace Magnum::Platform

// ═════════════════════════════════════════════════════════════════════════════
//  Magnum::Primitives
// ═════════════════════════════════════════════════════════════════════════════

GRAPHICS_EXPORT
namespace Magnum::Primitives
{
using Magnum::Primitives::coneSolid;
using Magnum::Primitives::cubeSolid;
using Magnum::Primitives::CylinderFlag;
using Magnum::Primitives::cylinderSolid;
using Magnum::Primitives::icosphereSolid;
using Magnum::Primitives::planeSolid;
// Enum-set operators
using Magnum::Primitives::operator|;
using Magnum::Primitives::operator&;
using Magnum::Primitives::operator^;
using Magnum::Primitives::operator~;

} // namespace Magnum::Primitives

// ═════════════════════════════════════════════════════════════════════════════
//  Magnum::SceneGraph
// ═════════════════════════════════════════════════════════════════════════════

GRAPHICS_EXPORT
namespace Magnum::SceneGraph
{

// Class templates
using Magnum::SceneGraph::Object;
using Magnum::SceneGraph::Scene;

// 3D typedefs
using Magnum::SceneGraph::AbstractFeature3D;
using Magnum::SceneGraph::Camera3D;
using Magnum::SceneGraph::Drawable3D;
using Magnum::SceneGraph::DrawableGroup3D;

// Transformation classes
using Magnum::SceneGraph::AbstractTranslationRotation3D;
using Magnum::SceneGraph::MatrixTransformation3D;

// Enums
using Magnum::SceneGraph::AspectRatioPolicy;
using Magnum::SceneGraph::CachedTransformation;

} // namespace Magnum::SceneGraph

// ═════════════════════════════════════════════════════════════════════════════
//  Magnum::Shaders
// ═════════════════════════════════════════════════════════════════════════════

GRAPHICS_EXPORT
namespace Magnum::Shaders
{
using Magnum::Shaders::PhongGL;
using Magnum::Shaders::VertexColorGL;
// Enum-set operators
using Magnum::Shaders::operator|;
using Magnum::Shaders::operator&;
using Magnum::Shaders::operator^;
using Magnum::Shaders::operator~;

} // namespace Magnum::Shaders

// ═════════════════════════════════════════════════════════════════════════════
//  Magnum::Trade
// ═════════════════════════════════════════════════════════════════════════════

GRAPHICS_EXPORT
namespace Magnum::Trade
{
using Magnum::Trade::MeshData;
} // namespace Magnum::Trade
